// Liyab — lookup tables of the GGML I-quant formats (internal).
//
// The tables themselves live in quant_tables.inc, generated by
// tools/gen_quant_tables.py. They are `inline constexpr` so the generic
// decoders (quant_ext.cpp) and the SIMD dot kernels (quant_lowbit.cpp) share a
// single copy in the binary (~33 KB) instead of one per translation unit.
//
// Layout matches llama.cpp's ggml-common.h byte for byte: kIq2xxsGrid[i] holds
// the 8 bytes of iq2xxs_grid[i] (a little-endian uint64), kIq3xxsGrid[i] the 4
// bytes of iq3xxs_grid[i], kIq1sGrid[i] the int8 values (-1, 0, +1) of
// iq1s_grid[i], kKSigns equals ksigns_iq2xs and kIq4nlValues kvalues_iq4nl.
#ifndef LIYAB_CORE_QUANT_TABLES_H
#define LIYAB_CORE_QUANT_TABLES_H

#include <cstdint>

namespace liyab::quant {

#include "core/quant_tables.inc"

}  // namespace liyab::quant

#endif  // LIYAB_CORE_QUANT_TABLES_H
