#!/usr/bin/env python3
"""Generates src/core/unicode_tables.inc: sorted code-point ranges for the
Unicode general categories L* (letters), N* (numbers) and M* (marks) used by
the BPE pre-tokenizer regexes (\\p{L}, \\p{N}, \\p{M}). Regenerate when updating Unicode:

    python3 tools/gen_unicode_tables.py > src/core/unicode_tables.inc
"""
import sys
import unicodedata


def ranges(predicate):
    out, start = [], None
    for cp in range(0x110000):
        if predicate(cp):
            if start is None:
                start = cp
        elif start is not None:
            out.append((start, cp - 1))
            start = None
    if start is not None:
        out.append((start, 0x10FFFF))
    return out


def emit(name, rs):
    print(f"// {len(rs)} ranges")
    print(f"constexpr CodepointRange {name}[] = {{")
    for i in range(0, len(rs), 4):
        print("    " + " ".join(f"{{0x{a:X}, 0x{b:X}}}," for a, b in rs[i:i + 4]))
    print("};")


print(f"// Generated by tools/gen_unicode_tables.py (Unicode {unicodedata.unidata_version}). Do not edit.")
emit("kLetterRanges", ranges(lambda c: unicodedata.category(chr(c)).startswith("L")))
emit("kNumberRanges", ranges(lambda c: unicodedata.category(chr(c)).startswith("N")))
emit("kMarkRanges", ranges(lambda c: unicodedata.category(chr(c)).startswith("M")))
