#!/usr/bin/env python3
"""Generates src/core/quant_tables.inc: the lattice grids and sign table of the
GGML I-quant formats (IQ1_S/IQ1_M, IQ2_XXS/XS/S, IQ3_XXS/S), extracted from the
reference implementation in llama.cpp's gguf-py package (MIT license).

    pip install gguf==0.19.0
    python3 tools/gen_quant_tables.py > src/core/quant_tables.inc
"""
import numpy as np
from gguf import quants


def grid(cls):
    cls.init_grid()
    return np.asarray(cls.grid, dtype=np.float32).reshape(cls.grid_shape).astype(np.int8)


def emit(name, ctype, rows):
    width = rows.shape[1] if rows.ndim == 2 else 0
    shape = f"[{rows.shape[0]}][{width}]" if width else f"[{rows.shape[0]}]"
    print(f"alignas(16) inline constexpr {ctype} {name}{shape} = {{")
    flat = rows.reshape(rows.shape[0], -1)
    for r in flat:
        print("    {" + ", ".join(str(int(v)) for v in r) + "}," if width else "    " + str(int(r[0])) + ",")
    print("};\n")


print("// Generated by tools/gen_quant_tables.py from gguf-py's reference I-quant grids. Do not edit.")
ksigns = np.frombuffer(quants.IQ2_XXS.ksigns, dtype=np.uint8)
print("inline constexpr uint8_t kKSigns[128] = {" + ", ".join(str(int(v)) for v in ksigns) + "};\n")
emit("kIq2xxsGrid", "uint8_t", grid(quants.IQ2_XXS).astype(np.uint8))
emit("kIq2xsGrid", "uint8_t", grid(quants.IQ2_XS).astype(np.uint8))
emit("kIq2sGrid", "uint8_t", grid(quants.IQ2_S).astype(np.uint8))
emit("kIq3xxsGrid", "uint8_t", grid(quants.IQ3_XXS).astype(np.uint8))
emit("kIq3sGrid", "uint8_t", grid(quants.IQ3_S).astype(np.uint8))
emit("kIq1sGrid", "int8_t", grid(quants.IQ1_S))
print("inline constexpr int8_t kIq4nlValues[16] = {" + ", ".join(str(v) for v in quants.IQ4_NL.kvalues) + "};")
print("inline constexpr int8_t kMxfp4Values[16] = {" + ", ".join(str(v) for v in quants.MXFP4.kvalues) + "};  // doubled e2m1")
