# Embeds compiled SPIR-V modules into a C++ header.
#   cmake -DOUT=<header> -DNAMES="a;b" -DINPUTS="a.spv;b.spv" -P embed_spirv.cmake
# Produces `static const unsigned char kSpv_<name>[]` arrays plus their sizes.
list(LENGTH INPUTS count)
math(EXPR last "${count} - 1")
set(content "// Generated by cmake/embed_spirv.cmake. Do not edit.\n#pragma once\n#include <cstddef>\n\n")
foreach(i RANGE ${last})
  list(GET INPUTS ${i} input)
  list(GET NAMES ${i} name)
  file(READ "${input}" hex HEX)
  string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")
  string(LENGTH "${hex}" hex_length)
  math(EXPR size "${hex_length} / 2")
  string(APPEND content "static const unsigned char kSpv_${name}[] = {${bytes}};\n")
  string(APPEND content "static const size_t kSpv_${name}_size = ${size};\n\n")
endforeach()
file(WRITE "${OUT}" "${content}")
